```{r message=FALSE, warning=FALSE}
####################################
#adatelőkészítés
####################################

#csomagok betöltése
library(dplyr)
library(lubridate)
library(ggplot2)
library(tidyr)
library(patchwork)
library(readxl)

#adatok beolvasása
iv_data <- read.csv("~/Downloads/HistoricalIV_AAPL.csv")
DGS1 <- read.csv("~/Downloads/DGS1.csv",stringsAsFactors = FALSE)

#dátum formátum
iv_data$Date <- as.Date(iv_data$Date, format = "%m/%d/%Y")

str(iv_data)
head(iv_data)

#elmúlt öt év adatainak kiszűrése

legfrissebb_datum <- max(iv_data$Date, na.rm = TRUE)
ot_eve <- legfrissebb_datum - years(5)

iv_data_5yr <- iv_data %>%
  filter(Date >= ot_eve)

#sigma_min és sigma_max meghatározása és tizedestörtté alakítása

sig_min <- min(iv_data_5yr$IV30, na.rm = TRUE) / 100
sig_max <- max(iv_data_5yr$IV30, na.rm = TRUE) / 100

cat("Vizsgált időszak:", as.character(ot_eve), "-tól", as.character(legfrissebb_datum), "\n")
cat("Kiszámolt sigma_min (Best case - Volatilitás):", sig_min, "\n")
cat("Kiszámolt sigma_max (Worst case - Volatilitás):", sig_max, "\n")

#treasury yield
r <- DGS1 %>%
  mutate(observation_date = ymd(observation_date)) %>%
  filter(observation_date == ymd("2026-04-08")) %>%
  pull(DGS1)

```

```{r message=FALSE, warning=FALSE}
####################################
#paraméterek beállítása
####################################

# AAPL Spot árfolyam
S0 <- 258.90 #2026.04.08 adj close

# Opciós paraméterek
K <- 260        # Kötési árfolyam
T <- 1.0        # Futamidő években
r <- r/100      # Kockázatmentes hozam

# Véges differencia rács létrehozása
S_max <- S0 * 2 # Rács felső határa
N <- 400        # Részvényárfolyam lépések száma
dS <- S_max / N # Részvényárfolyam lépésköz

# Stabilitási feltétel ellenőrzése
# dt < dS^2 / (sigma_max^2 * S_max^2)
dt_max <- (dS^2) / (sig_max^2 * S_max^2)
M <- ceiling(T / dt_max) + 2000 # ráhagyás a stabilitáshoz biztosításához
dt <- T / M

# Rács létrehozása
S <- seq(0, S_max, length.out = N + 1)

#Digitális Call kifizetési fv
V_upper <- ifelse(S > K, 1, 0)
V_lower <- ifelse(S > K, 1, 0)

#Explicit véges differenciák számítása Backward-módszerrel
# Belső csomópontok indexei
i <- 2:N

for (j in M:1) {
  V_up_old <- V_upper
  V_low_old <- V_lower
  
  #Worst-case
  Delta_up <- (V_up_old[i+1] - V_up_old[i-1]) / (2 * dS)
  Gamma_up <- (V_up_old[i+1] - 2 * V_up_old[i] + V_up_old[i-1]) / (dS^2)
  
  #sig_max ha Gamma > 0
  Sigma_up <- ifelse(Gamma_up > 0, sig_max, sig_min)
  
  V_upper[i] <- V_up_old[i] + dt * (
    0.5 * Sigma_up^2 * S[i]^2 * Gamma_up + 
    r * S[i] * Delta_up - 
    r * V_up_old[i]
  )
  
  #Best-case
  Delta_low <- (V_low_old[i+1] - V_low_old[i-1]) / (2 * dS)
  Gamma_low <- (V_low_old[i+1] - 2 * V_low_old[i] + V_low_old[i-1]) / (dS^2)
  
  #sig_min ha Gamma > 0
  Sigma_low <- ifelse(Gamma_low > 0, sig_min, sig_max)
  
  V_lower[i] <- V_low_old[i] + dt * (
    0.5 * Sigma_low^2 * S[i]^2 * Gamma_low + 
    r * S[i] * Delta_low - 
    r * V_low_old[i]
  )
  
  #Peremfeltételek:
V_upper[1] <- 0
V_lower[1] <- 0

t_current <- (j - 1) * dt
discount_factor <- exp(-r * (T - t_current))
V_upper[N+1] <- discount_factor
V_lower[N+1] <- discount_factor
}

#Eredmények Interpolálása a Spot Árra
price_upper <- approx(S, V_upper, xout = S0)$y
price_lower <- approx(S, V_lower, xout = S0)$y

cat("--- Uncertain Volatility Model - Digitális Call (AAPL) --- \n")
cat("Spot ár (S0):", S0, "\n")
cat("Kötési ár (K):", K, "\n")
cat("UVM Felső határ (Ask):", round(price_upper, 4), "\n")
cat("UVM Alsó határ (Bid):", round(price_lower, 4), "\n")
cat("Bid/Offer Spread:", round(price_upper - price_lower, 4), "\n\n")

```

```{r message=FALSE, warning=FALSE}
#ábrák 

# Adatok előkészítése a grafikonhoz
plot_range <- S > (K - 258.9) & S < (K + 258.9*2)
plot_data <- data.frame(
  StockPrice = S[plot_range],
  Felső_Határ = V_upper[plot_range],
  Alsó_Határ = V_lower[plot_range]
)

# 1. Ábra: UVM Árfolyam sáv
plot_prices <- ggplot(plot_data, aes(x = StockPrice)) +
  geom_ribbon(aes(ymin = Alsó_Határ, ymax = Felső_Határ), fill = "#FAD27B", alpha = 0.2) +
  geom_line(aes(y = Felső_Határ, color = "Felső határ (ask)"), size = 1) +
  geom_line(aes(y = Alsó_Határ, color = "Alsó határ (bid)"), size = 1) +
  
  # Piros függőleges vonal (spot)
  geom_vline(xintercept = S0, linetype = "dashed", color = "#660000", size = 1.2) +
  geom_label(aes(x = S0, y = max(plot_data$Felső_Határ) * 0.9, 
                 label = paste0("S(0): $", round(S0, 2))), 
             color = "#660000", fill = "white", label.size = 0.5, size = 3.5,
             vjust = -0.5, hjust = 1.1) +
  
  # Szürke függőleges vonal (strike)
  geom_vline(xintercept = K, linetype = "dotted", color = "#00FF00", size = 1.8) +
  geom_label(aes(x = K, y = min(plot_data$Felső_Határ) * 0.09,
                 label = paste0("Strike: $", round(K, 4))), 
             color = "#00FF00", fill = "white", label.size = 0.5, size = 3.5,
             vjust = -0.5, hjust = -0.1) +
  
  scale_color_manual(values = c("Felső határ (ask)" = "#C72C48", "Alsó határ (bid)" = "#20B2AA")) +
  labs(
    title = "Digitális call opció ársáv az UVM modellben",
    x = "Alaptermék árfolyama ($)",
    y = "Opció értéke",
    color = " "
  ) +
  theme_minimal() +
  theme(legend.position = "bottom")
plot_prices


# 2. Ábra: UVM Bid/Offer Spread
plot_data$Spread <- plot_data$Felső_Határ - plot_data$Alsó_Határ

plot_spread <- ggplot(plot_data, aes(x = StockPrice, y = Spread)) +
  geom_line(color = "#8A2BE2", size = 1) +
  
  # Piros függőleges vonal (spot)
  geom_vline(xintercept = S0, linetype = "dashed", color = "#660000", size = 1.2) +
  geom_label(aes(x = S0, y = max(plot_data$Spread) * 0.95,   
                 label = paste0("Spot: ", round(S0, 2))), 
             color = "#660000", fill = "white", label.size = 0.5, size = 3.5,
             vjust = -0.5, hjust = 1.1) +
  
  # Szürke függőleges vonal (strike)
  geom_vline(xintercept = K, linetype = "dotted", color = "#00FF00", size = 1.8) +
  geom_label(aes(x = K, y = max(plot_data$Spread) * 0.09,
                 label = paste0("Strike: ", round(K, 4))), 
             color = "#00FF00", fill = "white", label.size = 0.5, size = 3.5,
             vjust = -0.5, hjust = -0.1) +
  
  labs(
    title = "Digitális call opció bid-ask spread az UVM modellben",
    x = "Alaptermék árfolyama ($)",
    y = "Spread (ask - bid)"
  ) +
  theme_minimal() +
  theme(legend.position = "bottom")
plot_spread
```


```{r}
#------------------------------------------
#delta
#------------------------------------------

####################################
# Paraméterek
####################################

sigma <- mean(iv_data_5yr$IV30)/100 #sigmát beállítjuk az implikált volatilitások átlagára
sigma

maturities <- c(1.0, 0.5, 0.25, 0.10, 0.05, 0.01) # Lejáratok

# Részvényárfolyam-tartomány
S_grid <- seq(200, 320, by = 0.5)

####################################
# Digitális call delta függvény
####################################

digital_call_delta <- function(S, K, r, sigma, T) {
  d2 <- (log(S / K) + (r - 0.5 * sigma^2) * T) / (sigma * sqrt(T))
  delta <- exp(-r * T) * dnorm(d2) / (S * sigma * sqrt(T))
  return(delta)
}

####################################
# Adatbázis összeállítása
####################################

plot_data <- expand.grid(
  S = S_grid,
  T = maturities
) %>%
  arrange(T, S) %>%
  mutate(
    Delta = digital_call_delta(S, K, r, sigma, T),
    Lejarat = paste0("T = ", T, " év")
  )

####################################
# Ábra
####################################

delta_plot<- ggplot(plot_data, aes(x = S, y = Delta, color = Lejarat)) +
  geom_line(size = 1.1) +
  geom_vline(xintercept = K, linetype = "dashed", color = "black") +
  labs(
    title = "Digitális call opció deltája",
    x = "Alaptermék árfolyama ($)",
    y = expression(Delta),
    color = "Lejárat"
  ) +
  theme_minimal(base_size = 13) +
  theme(legend.position = "bottom")

#------------------------------------------
#gamma
#------------------------------------------
maturities <- c(1.0, 0.5, 0.25, 0.10, 0.05, 0.01)
S_grid <- seq(200, 320, by = 0.5)

####################################
# Digitális call gamma
####################################


digital_call_gamma <- function(S, K, r, sigma, T) {
  d2 <- (log(S / K) + (r - 0.5 * sigma^2) * T) / (sigma * sqrt(T))
  
  phi_d2 <- dnorm(d2)
  
  gamma <- exp(-r * T) * phi_d2 * (
    -d2 / (S^2 * sigma^2 * T) -
    1 / (S^2 * sigma * sqrt(T))
  )
  
  return(gamma)
}

####################################
# Adat
####################################

plot_data <- expand.grid(S = S_grid, T = maturities) %>%
  arrange(T, S) %>%
  mutate(
    Gamma = digital_call_gamma(S, K, r, sigma, T),
    Lejarat = paste0("T = ", T, " év")
  )

####################################
# Ábra
####################################

ylim_max <- max(plot_data$Gamma, na.rm = TRUE)
ylim_min <- min(plot_data$Gamma, na.rm = TRUE)

gamma_plot <- ggplot(plot_data, aes(x = S, y = Gamma, color = Lejarat)) +
  geom_line(size = 1.1) +
  geom_vline(xintercept = K, linetype = "dashed", color = "black") +
  geom_hline(yintercept = 0, color = "gray50") +
  
  coord_cartesian(ylim = c(ylim_min * 1.1, ylim_max * 1.1)) +
  
  labs(
    title = "Digitális call opció gammája",
    x = "Alaptermék árfolyama ($)",
    y = expression(Gamma),
    color = "Lejárat"
  ) +
  theme_minimal(base_size = 13) +
  theme(legend.position = "bottom")
delta_plot+gamma_plot
```

```{r}
################################
#statikus hedge
################################

#adatok beolvasása
call_data <- read_excel("Downloads/grid1_hc4m1vuz.xlsx")

#adatelőkészítés
call_data$Date <- as.Date(call_data$Date, format = "%m/%d/%Y")
call_data<-call_data %>%
  mutate(Date=Date+years(2000))

celt_datum <- ymd("2026-04-08") + years(1)

call_data <- call_data %>%
  mutate(eltolas = abs(Date - celt_datum))

min_eltolas <- min(call_data$eltolas, na.rm = TRUE)

call_data_szurt <- call_data %>%
  filter(eltolas == min_eltolas) %>%
  select(-eltolas)

bid250 <- call_data_szurt %>%
  filter(Strike == 250) %>%
  pull(Bid) %>%
  first()

ask250 <- call_data_szurt %>%
  filter(Strike == 250) %>%
  pull(Ask) %>%
  first()

bid270 <- call_data_szurt %>%
  filter(Strike == 270) %>%
  pull(Bid) %>%
  first()

ask270 <- call_data_szurt %>%
  filter(Strike == 270) %>%
  pull(Ask) %>%
  first()
```

```{r}
#------------------------------------------
# Statikus replikáció
#------------------------------------------

#paraméterek beállítása
K_lower <- 250
K_upper <- 270
spread_width <- K_upper - K_lower

# A szorzó, hogy a maximális kifizetés 1 dollár legyen
multiplier <- 1 / spread_width 

# A szintetikus digitális opció Bid/Ask árának meghatározása

# ASK eset: Eladjuk a digitális opciót az ügyfélnek (Ask ár).
# Fedezés: Veszünk egy Bull Call Spread-et.
# Megvesszük a 250-es Call-t Ask áron, eladjuk a 270-es Call-t Bid áron.
digital_ask_static <- (ask250 - bid270) * multiplier

# BID eset: Megvesszük a digitális opciót az ügyféltől (Bid ár).
# Fedezés: Eladunk egy Bull Call Spread-et.
# Eladjuk a 250-es Call-t Bid áron, megvesszük a 270-es Call-t Ask áron.
digital_bid_static <- (bid250 - ask270) * multiplier

#Spreadek kiszámítása és összehasonlítása
static_spread <- digital_ask_static - digital_bid_static
uvm_spread <- price_upper - price_lower

#Eredmények
cat("--- Statikus Replikáció ---\n")
cat("Alkalmazott kötési árak:", K_lower, "és", K_upper, "\n")
cat("Digitális Ask (Ügyfél veszi):", round(digital_ask_static, 4), "\n")
cat("Digitális Bid (Ügyfél eladja):", round(digital_bid_static, 4), "\n")
cat("Statikus bid/ask spread:", round(static_spread, 4), "\n\n")

cat("---Módszerek Összehasonlítása ---\n")
cat("1. UVM Spread:", round(uvm_spread, 4), "\n")
cat("2. Statikus Vanilla Spread:", round(static_spread, 4), "\n")
cat("=> A statikus fedezés ", round((1 - static_spread/uvm_spread) * 100, 2), "%-kal csökkentette az ársávot\n")
```

```{r message=FALSE, warning=FALSE}
#------------------------------------------
#ábrák
#------------------------------------------

# Árfolyam tartomány a kifizetés ábrázolásához
S_payoff <- seq(230, 290, by = 0.5)

# Kifizetések kiszámítása lejáratkor
Payoff_Long_Call <- pmax(S_payoff - K_lower, 0)
Payoff_Short_Call <- pmax(S_payoff - K_upper, 0)
Payoff_Call_Spread <- (Payoff_Long_Call - Payoff_Short_Call) * multiplier
Payoff_Digital_Ideal <- ifelse(S_payoff > K, 1, 0)

payoff_data <- data.frame(
  S = S_payoff,
  Replikacio = Payoff_Call_Spread,
  Digitalis = Payoff_Digital_Ideal
)


plot_replication <- ggplot(payoff_data, aes(x = S)) +
  #digitális kifizetés 
  geom_line(aes(y = Digitalis, color = "Digitális opció"), 
            linetype = "dashed", size = 1.2) +
  #replikáció kifizetés
  geom_line(aes(y = Replikacio, color = "Bull call spread"), 
            size = 1.5, alpha = 0.8) +
  
  geom_vline(xintercept = K_lower, linetype = "dotted", color = "gray20", 
             alpha = 0.7, size = 1.2) +
  geom_vline(xintercept = K_upper, linetype = "dotted", color = "gray20", 
             alpha = 0.7, size = 1.2) +
  
  annotate("label", x = K_lower, y = 0.5, 
           label = "K-ε ($250)", 
           angle = 90, vjust = -0.5, hjust = 0.5,
           fill = "white", color = "gray20", label.size = 0.3, size = 3.5) +
  annotate("label", x = K_upper, y = 0.5, 
           label = "K+ε ($270)", 
           angle = 90, vjust = 1.5, hjust = 0.5,
           fill = "white", color = "gray20", label.size = 0.3, size = 3.5) +
  
  scale_color_manual(values = c("Digitális opció" = "#2171B5", 
                                "Bull call spread" = "#C72C48")) +
  labs(
    title = "Bull call spread kifizetési függvénye",
    x = "Alaptermék árfolyama lejáratkor ($)",
    y = "Kifizetés ($)",
    color = " "
  ) +
  theme_minimal(base_size = 12) +
  theme(legend.position = "bottom")

plot_replication
```
```{r}

# Segédfüggvény a vanilla árak görbéjéhez
bs_call <- function(S, K, T, r, sigma) {
  d1 <- (log(S/K) + (r + 0.5*sigma^2)*T) / (sigma*sqrt(T))
  d2 <- d1 - sigma*sqrt(T)
  return(S*pnorm(d1) - K*exp(-r*T)*pnorm(d2))
}

sigma_mkt <- mean(iv_data_5yr$IV30)/100 

# Kiszámoljuk az elméleti spread értékeket a teljes S rácson
vanilla_250 <- bs_call(S, K_lower, T, r, sigma_mkt)
vanilla_270 <- bs_call(S, K_upper, T, r, sigma_mkt)
theoretical_spread <- (vanilla_250 - vanilla_270) * multiplier

# Korrigáljuk a görbéket a valós piaci Bid/Ask spread-del, mely biztosítja, hogy S0-nál pontosan a Bloomberg árakat lássuk
rep_ask_curve <- theoretical_spread + (digital_ask_static - approx(S, theoretical_spread, xout = S0)$y)
rep_bid_curve <- theoretical_spread - (approx(S, theoretical_spread, xout = S0)$y - digital_bid_static)


#Adatok ggplot-hoz
plot_range_combined <- S > (K-40) & S < (K+40)

combined_plot_data <- data.frame(
  StockPrice = S[plot_range_combined],
  UVM_Ask = V_upper[plot_range_combined],
  UVM_Bid = V_lower[plot_range_combined],
  Rep_Ask = rep_ask_curve[plot_range_combined],
  Rep_Bid = rep_bid_curve[plot_range_combined]
)

ggplot(combined_plot_data, aes(x = StockPrice)) +
  # UVM sáv
  geom_ribbon(aes(ymin = UVM_Bid, ymax = UVM_Ask, fill = "UVM Ársáv"), alpha = 0.2) +
  geom_line(aes(y = UVM_Ask), color = "#C72C48", linetype = "dashed", size = 0.5) +
  geom_line(aes(y = UVM_Bid), color = "#C72C48", linetype = "dashed", size = 0.5) +
  
  # Replikáló ársáv
  geom_ribbon(aes(ymin = Rep_Bid, ymax = Rep_Ask, fill = "Replikáló portfólió ársáv"), alpha = 0.6) +
  geom_line(aes(y = Rep_Ask), color = "#2171B5", size = 0.8) +
  geom_line(aes(y = Rep_Bid), color = "#2171B5", size = 0.8) +
  
  # Spot ár függőleges vonallal
  geom_vline(xintercept = S0, linetype = "dotted", color = "black", size = 1) +
  
  # Felirat dobozban (annotate label)
  annotate("label", x = S0, y = 0.9, 
           label = paste0("Spot: ", S0), 
           hjust = 1.1, vjust = 0.5,
           fill = "white", color = "black", 
           label.size = 0.3, size = 3.5) +
  
  scale_fill_manual(values = c("UVM Ársáv" = "#C72C48", 
                               "Replikáló portfólió ársáv" = "#2171B5")) +
  labs(
    title = "UVM  vs. replikáló portfólió ársáv",
    x = "Alaptermék árfolyama ($)",
    y = "Digitális opció értéke",
    fill = ""
  ) +
  theme_minimal() +
  theme(legend.position = "bottom")
```

```{r}
#-------------------------------------
#bull call spread delta & gamma
#-------------------------------------

####################################
# PARAMÉTEREK
####################################

maturities <- c(1.0, 0.5, 0.25, 0.10, 0.05, 0.01)
S_grid <- seq(230, 290, by = 0.5)

sigma_mkt <- mean(iv_data_5yr$IV30)/100

####################################
# VANILLA GÖRÖGÖK
####################################

vanilla_delta <- function(S, K, T, r, sigma) {
  d1 <- (log(S / K) + (r + 0.5 * sigma^2) * T) / (sigma * sqrt(T))
  pnorm(d1)
}

vanilla_gamma <- function(S, K, T, r, sigma) {
  d1 <- (log(S / K) + (r + 0.5 * sigma^2) * T) / (sigma * sqrt(T))
  dnorm(d1) / (S * sigma * sqrt(T))
}

####################################
# STATIKUS REPLIKÁCIÓ GÖRÖGJEI
####################################

plot_data <- expand.grid(S = S_grid, T = maturities) %>%
  mutate(
    Delta = (vanilla_delta(S, K_lower, T, r, sigma_mkt) -
             vanilla_delta(S, K_upper, T, r, sigma_mkt)) * multiplier,
    
    Gamma = (vanilla_gamma(S, K_lower, T, r, sigma_mkt) -
             vanilla_gamma(S, K_upper, T, r, sigma_mkt)) * multiplier,
    
    Lejarat = paste0("T = ", T, " év")
  )

####################################
# DELTA ÁBRA
####################################

####################################
# DELTA ÁBRA – STATIKUS HEDGE
####################################

delta_plot_rep <- ggplot(plot_data, 
                         aes(x = S, y = Delta, color = Lejarat)) +
  geom_line(size = 1.2) +
  
  # Strike jelölése
  geom_vline(xintercept = K, 
             linetype = "dashed", 
             color = "black") +
  
  # Y tengely korlátozás
  coord_cartesian(ylim = c(0, 0.06)) +
  
  labs(
    title = "Bull call spread deltája",
    x = "Alaptermék árfolyama ($)",
    y = expression(Delta),
    color = "Lejárat"
  ) +
  
  theme_minimal(base_size = 13) +
  theme(
    legend.position = "bottom"
  )

####################################
# GAMMA ÁBRA
####################################

gamma_plot_rep <- ggplot(plot_data, 
                         aes(x = S, y = Gamma, color = Lejarat)) +
  geom_line(size = 1.2) +
  geom_vline(xintercept = K, linetype = "dashed", color = "black") +
  geom_hline(yintercept = 0, color = "gray50") +
  coord_cartesian(ylim = c(-0.006, 0.006)) +
  labs(
    title = "Bull call spread gammája",
    x = "Alaptermék árfolyama ($)",
    y = expression(Gamma),
    color = "Lejárat"
  ) +
  theme_minimal(base_size = 13) +
  theme(legend.position = "bottom")

####################################
# ÖSSZEFŰZÉS
####################################

delta_plot_rep + gamma_plot_rep

```

